In [35]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
a[:,1]

array([2, 5])

In [41]:
a[1,0:5:2]

array([ 6,  8, 10])

In [5]:
#dimension
a.ndim

2

In [7]:
#shape
a.shape

(2, 3)

In [9]:
#bytesize
a.itemsize

4

In [11]:
#datatype
a.dtype

dtype('int32')

In [13]:
#size
a.size

6

In [15]:
#totalsize
a.nbytes


24

In [19]:
#reshaping
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a.sqrt

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [27]:
a.sum(0,1)

TypeError: Cannot interpret '1' as a data type

In [43]:
output=np.zeros((4,4))
a=np.ones((2,2))
output[1:3,1:3]=a
print(output)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
