In [5]:
import numpy as np
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#chcking dimension
array.shape

(10,)

In [22]:
#creating 2d
array=np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
#zeros,ones,full,empty
a1=np.zeros((2,2))
a2=np.ones((2,2))
a3=np.full((2,3),3)
a4=np.empty((2,2))
print(a1)
print(a2)
print(a3)
print(a4)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3 3 3]
 [3 3 3]]
[[1. 1.]
 [1. 1.]]


In [70]:
#identity
a5=np.eye(3)
a5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
#random
a6=np.random.rand(2,2)
a6

array([[0.45609844, 0.28601354],
       [0.19474264, 0.64073224]])

In [88]:
#linspace
a7=np.linspace(1,10,num=5)
a7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])