In [27]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print("arr1:\n",arr1)
arr2=np.array([[7,8,9],[10,11,12]])
print("arr1:\n",arr1)
arr=np.concatenate((arr1,arr2),axis=0)
print("concatenated array:\n",arr)


arr1:
 [[1 2 3]
 [4 5 6]]
arr2:
 [[ 7  8  9]
 [10 11 12]]
concatenated array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8])
print("array:\n",array)
arr=np.split(array,8)
print(arr)




array:
 [1 2 3 4 5 6 7 8]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8])]


In [42]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8])
print("array:\n",array)
arr=np.array_split(array,9)
print(arr)

array:
 [1 2 3 4 5 6 7 8]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([], dtype=int32)]


In [49]:
import numpy as np
array=np.array([[1,2],[3,4],[5,6],[7,8]])
print("array:\n",array)
arr=np.array_split(array,3)
print(arr)

array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [62]:
import numpy as np
array=np.array([[1,2],[3,4],[5,6],[7,8]])
print("array:\n",array)
arr=np.hsplit(array,2)
print(arr)

array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [64]:
import numpy as np
array=np.array([[1,2],[3,4],[5,6],[7,8]])
print("array:\n",array)
arr=np.vsplit(array,2)
print(arr)

array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [70]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8])
print("array:\n",array)
arr=np.hsplit(array,2)
print(arr)

array:
 [1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [68]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8])
print("array:\n",array)
arr=np.vsplit(array,8)
print(arr)

array:
 [1 2 3 4 5 6 7 8]


ValueError: vsplit only works on arrays of 2 or more dimensions

In [98]:
import numpy as np
array=np.array([[1,2,3],
                [3,4,5],
                [1,2,3]])
print("array:\n",array)
print("Rank:\n",np.linalg.matrix_rank(array))
print("\nTrace:\n",np.trace(array))
print("\nDeterminent:\n",np.linalg.det(array))
print("\nInverse:\n",np.linalg.inv(array))
print("\nMatrix raised to the power 3:\n",np.linalg.matrix_power(array,3))

array:
 [[1 2 3]
 [3 4 5]
 [1 2 3]]
Rank:
 2

Trace:
 8

Determinent:
 0.0


LinAlgError: Singular matrix

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
